<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>AbsoluteHostMod</AssemblyName>
    <RootNamespace>AbsoluteHostMod</RootNamespace>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-*" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.Core" Version="5.4.*" IncludeAssets="compile" />
    <PackageReference Include="Reactor.Latest" Version="*" IncludeAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>libs/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Netcode.Runtime">
      <HintPath>libs/Unity.Netcode.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
