<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>AbsoluteHostMod</AssemblyName>
    <RootNamespace>AbsoluteHostMod</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Reactor" Version="2.3.1" />
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.679" Private="false" ExcludeAssets="runtime;native" />
    <PackageReference Include="AmongUs.GameLibs.Steam" Version="2026.6.5" PrivateAssets="all" />
  </ItemGroup>

</Project>
